name: base
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # Conda packages
  - python=3.10
  - numpy=1.22
  - pandas<2.2.0 # See https://github.com/ICB-DCM/pyABC/issues/632
  - h5py=3.6
  - scikit-learn=1.0
  - scipy
  - pip
  - hdbscan
  - Pillow
  # - pytorch
  # - torchvision
  - hiredis
  - joblib==1.1.0 # See https://github.com/scikit-learn-contrib/hdbscan/issues/562

  - pip:
    - gunicorn
    - flask>=1.0.2,<2
    - werkzeug < 2.1 #See https://github.com/morphocluster/morphocluster/issues/66
    - psycopg2-binary
    - sqlalchemy>=1.3,<2
    - etaprogress
    - h5py>=3.1.0
    - scikit-learn
    - scipy
    - redis>=3.5.0
    - hiredis
    - flask-restful
    - alembic
    - Flask-SQLAlchemy
    - flask-redis
    - Flask-Migrate
    - timer_cm
    - fire
    - marshmallow
    - match_arrays
    - Flask-RQ2
    - tqdm
    - hdbscan
    - chardet
    - environs  # For envvar parsing
    - markupSafe<=2.0.1
    - Jinja2<3.1
    - itsdangerous==2.0.1