version: '3'
services:
  morphocluster:
    build:
      context: . # Relative to project root
      dockerfile: .devcontainer/dev.Dockerfile
    environment:
      - FLASK_ENV=development

    volumes:
      - .:/workspace/morphocluster

    depends_on:
      - postgres
      - redis-lru

    # # Overrides default command so things don't shut down after the process ends.
    # command: sleep infinity

    # Run service on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:postgres
    # Uncomment the next line to use a non-root user for all processes.
    # user: mambauser
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  # We use a named volume so that the data is not lost if the image is rebuilt
  postgres-data:

  morphocluster-data:
    # Store application data in a host directory
    driver: local
    driver_opts:
      o: bind
      type: none
      device: .devcontainer/data
