name: Black (python)

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup Python env
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install black
        run: pip install black

      - name: Run black on all Python files
        run: |
          black --check .
